#!/bin/sh
[ -s ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_prerm $0 $@

# Stop the service before removing the package.
[ -z "${IPKG_INSTROOT}" ] && /etc/init.d/nbtverify stop 2>/dev/null

exit 0
